# Node.js with Eleventy
# Build a Node.js project.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
trigger:
  - master

pool:
  vmImage: "ubuntu-16.04"

steps:
  - checkout: self
    persistCredentials: true

  - task: NodeTool@0
    inputs:
      versionSpec: "9.x"
    displayName: "Install Node.js"

  - script: |
      npm install --save-dev
    displayName: "npm install"

  - script: |
      npm run build
    displayName: "run build"

  - task: CopyFiles@2
    displayName: "Copy Files to: $(Build.ArtifactStagingDirectory)"
    inputs:
      SourceFolder: "$(Build.SourcesDirectory)"
      Contents: |
        *
        **/*
        !node_modules/**/*
      TargetFolder: "$(Build.ArtifactStagingDirectory)"

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: "$(Build.ArtifactStagingDirectory)"

  - bash: |
      echo "check git settings"
      echo build dir $(Build.Repository.LocalPath)
      echo build srouce dir : $(Build.SourcesDirectory)
      echo staging dir: $(Build.StagingDirectory)

      git status
      #git config user.name "marc modin"

      echo "the branch from build :" $(Build.SourceBranchName)
      git checkout $(Build.SourceBranchName)
      git stash
      #git commit -a --allow-empty -m '$(Build.SourceBranchName)'

      echo check current branch 
      git checkout master
      git ls-a -a
      #git branch build
      #git checkout build
      echo about to push to $(Build.Repository.Name)
      #git push --set-upstream origin HEAD:build

    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)
