# Node.js with Eleventy
# Build a Node.js project.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
trigger:
  - master

pool:
  vmImage: "ubuntu-16.04"

steps:
  - checkout: self
    persistCredentials: true

  - task: NodeTool@0
    inputs:
      versionSpec: "9.x"
    displayName: "Install Node.js"

  - script: |
      npm install --save-dev
    displayName: "npm install"
  - script: |
      npm run build
    displayName: "run build"
    
  - bash: |
      # git settings
      echo "check git settings"
      git config user.name "marc modin"
      echo fetch from origin again
      git fetch
      # Build Sources Directory is /home/vsts/work/1/s
      echo here we should stage docs at: $(Build.Repository.LocalPath)
      echo build dir is at : $(Build.SourcesDirectory)
      dir
      echo creating a new build branch
      git checkout -b build
      
      echo add all new files to branch
      git add .
      git commit -a --allow-empty -m 'committing build'
      
      echo git fetch and diff 
      
      echo fething from remote to check diff
      git diff
      git status
      
      #git branch build
      #git checkout build
      #echo about to push to $(Build.Repository.Name)
      git push --set-upstream origin HEAD:build
      git checkout master
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)
      
#   - task: CopyFiles@2
#     displayName: "Copy Files to: $(Build.ArtifactStagingDirectory)"
#     inputs:
#       SourceFolder: "$(Build.SourcesDirectory)"
#       Contents: |
#         *
#         **/*
#         !node_modules/**/*
#       TargetFolder: "$(Build.ArtifactStagingDirectory)"

#   - task: PublishBuildArtifacts@1
#     inputs:
#       PathtoPublish: "$(Build.ArtifactStagingDirectory)"
