# Node.js with Eleventy
# Build a Node.js project.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  vmImage: "ubuntu-16.04"

steps:
  - checkout: self
    persistCredentials: true  

  - task: NodeTool@0
    inputs:
      versionSpec: "9.x"
    displayName: "Install Node.js"

  - script: |
      npm install --save-dev
    displayName: "npm install"
    
  - script: |
      npm run build
    displayName: "run build"
    
  - script: |
     git add . 
     git commit -a 
    displayName: "push back to github"   
  
  - task: CopyFiles@2
    displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)'
      Contents: |
        **/*
        !node_modules/**/*
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
      
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'

