# Node.js with Eleventy
# Build a Node.js project.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
trigger:
# - master
# - build

pool:
  vmImage: "vs2017-win2016"

steps:
  - checkout: self
    persistCredentials: true

  - script: |
      npm install --save-dev
    displayName: "npm install"
    
  - script: |
      npm run build
    displayName: "run build"
    
  - bash: |
  
      echo "checking git settings"
      git config user.name "marc modin"

      echo fetch from origin again
      git pull origin master
      # Build Sources Directory is /home/vsts/work/1/s
      echo here we should stage docs at: $(Build.Repository.LocalPath)
      dir
      
      echo checking branches
      # git checkout -b build
      git branch
      
      echo and checking out master
      git checkout master
      git pull origin master
      
      echo add all new files to branch
      git add -fA
      git commit -a --allow-empty -m '$(git log build -1 --pretty=%B)'
      
      echo the git diff and status :  
      
      git diff
      git status
      
      echo about to push to $(Build.Repository.Name)
      #git push --set-upstream origin HEAD:build
      git push origin master
      
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)
      
#   - task: CopyFiles@2
#     displayName: "Copy Files to: $(Build.ArtifactStagingDirectory)"
#     inputs:
#       SourceFolder: "$(Build.SourcesDirectory)"
#       Contents: |
#         *
#         **/*
#         !node_modules/**/*
#       TargetFolder: "$(Build.ArtifactStagingDirectory)"

#   - task: PublishBuildArtifacts@1
#     inputs:
#       PathtoPublish: "$(Build.ArtifactStagingDirectory)"
