# Node.js with Eleventy
# Build a Node.js project.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
trigger:
  - build/**

pool:
  vmImage: "ubuntu-16.04"

steps:
  - checkout: self
    persistCredentials: true

  - script: |
      npm install --save-dev
    displayName: "npm install"

  - script: |
      npm run clean & npm run build
    displayName: "run build"

  - bash: |

      echo "checking git settings"
      git config user.name "marc modin"

      # Build Sources Directory should be /home/vsts/work/1/s
      echo here we should stage docs at: $(Build.Repository.LocalPath)

      echo and checking out build
      git checkout build
      git pull origin build

      echo add all new files to branch
      git add --all
      git add docs/**
      git commit -a --allow-empty -m "$(Build.SourceVersion)"

      echo the git diff and status :  

      git diff
      git status

      echo about to push to $(Build.Repository.Name)
      #git push --set-upstream origin HEAD:build
      git push origin build

    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)
#   - task: CopyFiles@2
#     displayName: "Copy Files to: $(Build.ArtifactStagingDirectory)"
#     inputs:
#       SourceFolder: "$(Build.SourcesDirectory)"
#       Contents: |
#         *
#         **/*
#         !node_modules/**/*
#       TargetFolder: "$(Build.ArtifactStagingDirectory)"

#   - task: PublishBuildArtifacts@1
#     inputs:
#       PathtoPublish: "$(Build.ArtifactStagingDirectory)"
